"""empty message

Revision ID: 203aab30604a
Revises: 9f258b8ff3bd
Create Date: 2026-09-20 14:06:13.016179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '203aab30604a'
down_revision: Union[str, None] = '9f258b8ff3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_ruian_id_key', 'addresses', type_='unique')
    op.create_unique_constraint(op.f('uq_addresses_ruian_id'), 'addresses', ['ruian_id'])
    op.drop_constraint('banks_code_key', 'banks', type_='unique')
    op.drop_constraint('banks_swift_code_key', 'banks', type_='unique')
    op.create_unique_constraint(op.f('uq_banks_code'), 'banks', ['code'])
    op.create_unique_constraint(op.f('uq_banks_swift_code'), 'banks', ['swift_code'])
    op.drop_constraint('business_customers_customer_id_key', 'business_customers', type_='unique')
    op.create_unique_constraint(op.f('uq_business_customers_customer_id'), 'business_customers', ['customer_id'])
    op.drop_constraint('countries_code_key', 'countries', type_='unique')
    op.create_unique_constraint(op.f('uq_countries_code'), 'countries', ['code'])
    op.drop_constraint('emails_address_key', 'emails', type_='unique')
    op.create_unique_constraint(op.f('uq_emails_address'), 'emails', ['address'])
    op.drop_constraint('entity_types_name_key', 'entity_types', type_='unique')
    op.create_unique_constraint(op.f('uq_entity_types_name'), 'entity_types', ['name'])
    op.drop_constraint('individual_customers_customer_id_key', 'individual_customers', type_='unique')
    op.create_unique_constraint(op.f('uq_individual_customers_customer_id'), 'individual_customers', ['customer_id'])
    op.drop_constraint('phones_number_key', 'phones', type_='unique')
    op.create_unique_constraint(op.f('uq_phones_number'), 'phones', ['number'])
    op.drop_constraint('proprietor_customers_customer_id_key', 'proprietor_customers', type_='unique')
    op.create_unique_constraint(op.f('uq_proprietor_customers_customer_id'), 'proprietor_customers', ['customer_id'])
    op.add_column('refresh_token', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refresh_token', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_refresh_token_session_id'), 'refresh_token', ['session_id'], unique=False)
    op.drop_column('refresh_token', 'expired_at')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    op.create_index(op.f('ix_sessions_external_id'), 'sessions', ['external_id'], unique=True)
    op.alter_column('titles', 'title_type',
               existing_type=postgresql.ENUM('prefix', 'suffix', name='titletype'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('user_customers_customer_id_key', 'user_customers', type_='unique')
    op.create_unique_constraint(op.f('uq_user_customers_customer_id'), 'user_customers', ['customer_id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_user_customers_customer_id'), 'user_customers', type_='unique')
    op.create_unique_constraint('user_customers_customer_id_key', 'user_customers', ['customer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('titles', 'title_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('prefix', 'suffix', name='titletype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sessions_external_id'), table_name='sessions')
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('refresh_token', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_token_session_id'), table_name='refresh_token')
    op.drop_column('refresh_token', 'valid_to')
    op.drop_column('refresh_token', 'valid_from')
    op.drop_constraint(op.f('uq_proprietor_customers_customer_id'), 'proprietor_customers', type_='unique')
    op.create_unique_constraint('proprietor_customers_customer_id_key', 'proprietor_customers', ['customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_phones_number'), 'phones', type_='unique')
    op.create_unique_constraint('phones_number_key', 'phones', ['number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_individual_customers_customer_id'), 'individual_customers', type_='unique')
    op.create_unique_constraint('individual_customers_customer_id_key', 'individual_customers', ['customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_entity_types_name'), 'entity_types', type_='unique')
    op.create_unique_constraint('entity_types_name_key', 'entity_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_emails_address'), 'emails', type_='unique')
    op.create_unique_constraint('emails_address_key', 'emails', ['address'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_countries_code'), 'countries', type_='unique')
    op.create_unique_constraint('countries_code_key', 'countries', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_business_customers_customer_id'), 'business_customers', type_='unique')
    op.create_unique_constraint('business_customers_customer_id_key', 'business_customers', ['customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_banks_swift_code'), 'banks', type_='unique')
    op.drop_constraint(op.f('uq_banks_code'), 'banks', type_='unique')
    op.create_unique_constraint('banks_swift_code_key', 'banks', ['swift_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('banks_code_key', 'banks', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_addresses_ruian_id'), 'addresses', type_='unique')
    op.create_unique_constraint('addresses_ruian_id_key', 'addresses', ['ruian_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
