"""empty message

Revision ID: 809a68f2735f
Revises: 203aab30604a
Create Date: 2026-09-22 10:08:02.727181

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809a68f2735f'
down_revision: str | None = '203aab30604a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'valid_to')
    op.drop_column('titles', 'valid_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('titles', sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
