"""empty message

Revision ID: fff92843aa8b
Revises: a6383003f4da
Create Date: 2026-10-03 13:52:17.377149

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fff92843aa8b'
down_revision: str | None = 'a6383003f4da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_types', sa.Column('type', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_address_types_type'), 'address_types', ['type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_address_types_type'), 'address_types', type_='unique')
    op.drop_column('address_types', 'type')
    # ### end Alembic commands ###
